apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-scaler
  namespace: keda-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-scaler
  template:
    metadata:
      labels:
        app: keda-scaler
    spec:
      containers:
      - name: keda-scaler
        image: venkateshsrini3/deploy-scaler:1.3
        ports:
        - containerPort: 60051
        env:
        - name: keda-namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GrpcPort
          value: "60051"
        - name: MongoDB__connectionString
          valueFrom:
            secretKeyRef:
              name: mongo-db-secrets
              key: connectionString
---
apiVersion: v1
kind: Service
metadata:
  name: keda-scaler
  namespace: keda-sample
spec:
  selector:
    app: keda-scaler
  ports:
  - protocol: TCP
    port: 80
    targetPort: 60051
  type: ClusterIP