apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-scaler
  template:
    metadata:
      labels:
        app: keda-scaler
    spec:
      containers:
      - name: keda-scaler
        image: venkateshsrini3/deploy-scaler:1.1
        ports:
        - containerPort: 60051
        env:
        - name: keda-namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GrpcPort
          value: "60051"
---
apiVersion: v1
kind: Service
metadata:
  name: keda-scaler
spec:
  selector:
    app: keda-scaler
  ports:
  - protocol: TCP
    port: 80
    targetPort: 60051
    type: ClusterIP