apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaler-control-plain-deployment
  namespace: keda-sample
  labels:
    app: scaler-control-plain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaler-control-plain
  template:
    metadata:
      labels:
        app: scaler-control-plain
    spec:
      containers:
      - name: scaler-control-plain
        image: venkateshsrini3/control-plane:1.1 # Replace with your Docker image
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: MongoDB__connectionString
          valueFrom:
            secretKeyRef:
              name: mongo-db-secrets
              key: connectionString
---
apiVersion: v1
kind: Service
metadata:
  name: scaler-control-plain-service
  namespace: keda-sample
  labels:
    app: scaler-control-plain
spec:
  selector:
    app: scaler-control-plain
  ports:
  - protocol: TCP
    port: 3007
    targetPort: 8080
  type: LoadBalancer
